### ISSUE TITLE
How to build it?

### ISSUE THREAD

**Issue by traysh** [KerseyFabrications/marlin_e5p#3]
I see there is a Makefile in Marlin folder. How do I use it to build the firmware?

Thanks in advance

**Comment by jimberg98** [comment]
> I see there is a Makefile in Marlin folder. How do I use it to build the firmware?
> 
> Thanks in advance

Building it is one of the best guarded secrets for some reason.

Have you tried using the Arduino IDE?

EDIT: I was able to build it with the Arduino IDE. It's strange how it works. I opened the MAKEFILE (I don't think the file you pick matters as long as it's in the folder with the source code), selected Tools and set my board type to 'Arduino Mega or Arduino Mega 2560' and then selected Verify/Compile from the Sketch menu. I haven't uploaded it yet, so stay tuned.

**Comment by traysh** [comment]
I did not. Probably it is a good start.

Em sex., 14 de mai. de 2021 às 09:51, jimberg98 ***@***.***>
escreveu:

**Comment by traysh** [comment]
Ok, I did it both using the IDE and arduino-cli.

To build it using arduino-cli, I run:
```
arduino-cli compile -b arduino:avr:mega -v --clean -e
```

in `Marlin` folder.

`arduino-cli` docs can be found here: https://www.arduino.cc/pro/cli

**Comment by KerseyFabrications** [comment]
Sorry for the delay all. I don't do a lot of interacting directly on GitHub usually but I'll add it to my list. I'll get back to you on specifics but what has been said is correct. For this release, you have to use the Arduino IDE because it's based on an old Marlin release. You can select the Arduino Mega or Mega 2560 under Arduino AVR Boards. Then you can upload it directly connected to the board. I hope this is something "more official."
